
analyzer:
  exclude:
    - build/**
    - android/**
    - ios/**
    - web/**
    - windows/**
    - macos/**
    - linux/**
include: package:flutter_lints/flutter.yaml

linter:

  rules:
    avoid_print: false  # Uncomment to disable the `avoid_print` rule
    prefer_single_quotes: true 
    prefer_const_constructors: true
    always_use_package_imports: true
    always_declare_return_types: true
    type_annotate_public_apis: true
