name: portafolio_app
description: "A personal portfolio app built with Flutter showcasing my
  projects, skills, and certifications."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.2

dependencies:
  carousel_slider: ^5.0.0
  cupertino_icons: ^1.0.8
  firebase_core: ^3.12.1
  flutter:
    sdk: flutter
  font_awesome_flutter: ^10.1.0
  go_router: ^14.8.0
  http: ^1.3.0
  provider: ^6.1.2
  smooth_page_indicator: ^1.2.1
  universal_html: ^2.2.4
  url_launcher: ^6.3.1
  video_player: ^2.9.3

dev_dependencies:

  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/docs/curriculum_mobile.pdf
    - assets/images/profile.webp
    - assets/images/commingSoon.webp
    - assets/images/projects/portfolio/inicio.webp
    - assets/images/projects/portfolio/about_me1.webp
    - assets/images/projects/portfolio/about_me2.webp
    - assets/images/projects/portfolio/services1.webp
    - assets/images/projects/portfolio/services2.webp
    - assets/images/projects/pomodoro/break.webp
    - assets/images/projects/pomodoro/data.webp
    - assets/images/projects/pomodoro/history.webp
    - assets/images/projects/pomodoro/init.webp
    - assets/images/projects/pomodoro/session.webp
    - assets/certificate/English.webp
    - assets/certificate/flutter.webp
    - assets/certificate/frontend.webp
    - assets/certificate/meditacion.webp
    - assets/certificate/feedback.webp
    - assets/certificate/blandas.webp
    - assets/certificate/marcaPersonal.webp
    - assets/certificate/productividad.webp
    - assets/videos/portfolio.mp4
    - assets/images/projects/yellow_flowers/fase1.webp
    - assets/images/projects/yellow_flowers/fase2.webp
    - assets/images/projects/yellow_flowers/fase20.webp
    - assets/images/projects/yellow_flowers/idea.webp
    - assets/images/projects/parroquia/login_parroquia.webp
