name: flutter_portfolio
description: "A personal portfolio app built with Flutter showcasing my
  projects, skills, and certifications."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.2

dependencies:
  carousel_slider: ^5.0.0
  cupertino_icons: ^1.0.8
  firebase_core: ^3.12.1
  flutter:
    sdk: flutter
  font_awesome_flutter: ^10.1.0
  go_router: ^14.8.0
  http: ^1.3.0
  provider: ^6.1.2
  smooth_page_indicator: ^1.2.1
  url_launcher: ^6.3.1
  video_player: ^2.9.3

dev_dependencies:

  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  fonts:
    - family: NotoSans
      fonts:
        - asset: assets/fonts/NotoSans-Regular.ttf
        - asset: assets/fonts/NotoSans-Bold.ttf
          weight: 700

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/profile.webp
    - assets/images/commingSoon.webp
    - assets/images/projects/portfolio/inicio.png
    - assets/images/projects/portfolio/about_me1.png
    - assets/images/projects/portfolio/about_me2.png
    - assets/images/projects/portfolio/services1.png
    - assets/images/projects/portfolio/services2.png
    - assets/images/projects/pomodoro/break.webp
    - assets/images/projects/pomodoro/data.webp
    - assets/images/projects/pomodoro/history.webp
    - assets/images/projects/pomodoro/init.webp
    - assets/images/projects/pomodoro/session.webp
    - assets/certificate/English.png
    - assets/certificate/flutter.png
    - assets/certificate/frontend.png
    - assets/certificate/meditacion.png
    - assets/certificate/feedback.png
    - assets/certificate/blandas.png
    - assets/certificate/marcaPersonal.png
    - assets/certificate/productividad.png
    - assets/videos/portfolio.mov
    - assets/images/projects/yellow_flowers/fase1.png
    - assets/images/projects/yellow_flowers/fase2.png
    - assets/images/projects/yellow_flowers/fase20.png
    - assets/images/projects/yellow_flowers/idea.png
    - assets/images/projects/eduplay/menu_web.webp
  #   - images/a_dot_ham.jpeg
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
