name: portafolio_app
description: "A personal portfolio app built with Flutter showcasing my
  projects, skills, and certifications."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.2

dependencies:
  carousel_slider: ^5.0.0
  cupertino_icons: ^1.0.8
  firebase_core: ^3.12.1
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  font_awesome_flutter: ^10.1.0
  google_fonts: ^6.2.1
  url_launcher: ^6.3.1
  go_router: ^14.8.0
  http: ^1.3.0
  provider: ^6.1.2
  smooth_page_indicator: ^1.2.1
  universal_html: ^2.2.4
  video_player: ^2.9.3

  intl: any
dev_dependencies:

  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true
  generate: true

  assets:
  - assets/images/
  # Ensure nested project image folders are bundled on Web
  - assets/images/projects/
  - assets/images/projects/portfolio/
  - assets/images/projects/pomodoro/
  - assets/images/projects/eduplay/
  - assets/images/projects/parroquia/
  - assets/images/projects/yellow_flowers/
  - assets/images/projects/tropigas/
  - assets/images/projects/personal_finance/
  - assets/certificate/
  - assets/videos/
