name: Deploy Flutter Web to Firebase Hosting

on:
  push:
    branches:
      - main  # Se ejecutará cuando hagas push en la rama main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 3.29.1  # Asegurar versión correcta de Flutter

      - name: Verificar versión de Flutter
        run: flutter --version

      - name: Limpiar y reconstruir
        run: |
          flutter clean
          flutter pub get
          flutter build web --release

      - name: Verificar archivos después de build
        run: ls -la build/

      - name: Verificar archivos en build/web
        run: ls -la build/web || echo "⚠️ build/web no existe"

      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      - name: Deploy to Firebase Hosting
        run: firebase deploy --token ${{ secrets.FIREBASE_TOKEN }}